/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT stills_R_Wsdfdsgfsdhfghggfh.cdb */

/*  Include Header File  */
#include "stills_R_Wsdfdsgfsdhfghggfhcfg.h"

/*  Config Structures */
/*  Handles  */
